// flow-typed signature: e8d55945f2624a27c584eb19ebe3710f
// flow-typed version: <<STUB>>/strict-loader_v^1.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strict-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strict-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'strict-loader/index' {
  declare module.exports: $Exports<'strict-loader'>;
}
declare module 'strict-loader/index.js' {
  declare module.exports: $Exports<'strict-loader'>;
}
